# Generated by Django 4.1.7 on 2023-06-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_amostra_experimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amostra',
            old_name='valor',
            new_name='concentracao',
        ),
        migrations.AddField(
            model_name='amostra',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
    ]
